/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const modelPath = "/robot.gltf";

export function Robot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(modelPath);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="head"
          castShadow
          receiveShadow
          geometry={nodes.head.geometry}
          material={nodes.head.material}
          position={[0, -5.08, 0.5]}
          scale={1.05}
        />
        <mesh
          name="rightarm"
          castShadow
          receiveShadow
          geometry={nodes.rightarm.geometry}
          material={nodes.rightarm.material}
          scale={[1, 2, 1]}
        />
        <mesh
          name="leftarm"
          castShadow
          receiveShadow
          geometry={nodes.leftarm.geometry}
          material={nodes.leftarm.material}
          scale={[1, 2, 1]}
        />
        <mesh
          name="body"
          castShadow
          receiveShadow
          geometry={nodes.body.geometry}
          material={nodes.body.material}
          scale={[1, 2, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);

